items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('create/', views.item_create, name='item_create'),
    path('<int:item_id>/', views.item_detail, name='item_detail'),
    path('<int:item_id>/update/', views.item_update, name='item_update'),
    path('<int:item_id>/delete/', views.item_delete, name='item_delete'),
    path('<int:item_id>/toggle_like/', views.toggle_like, name='toggle_like'),
]

market_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('items/', include('items.urls')),
    path('users/', include('users.urls')),

]

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, CustomLogoutView, ProfileView, LikedItemsListView, FollowersListView, FollowingListView, follow


app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('<str:username>/liked-items/', LikedItemsListView.as_view(), name='liked_items_list'),
    path('<str:username>/followers/', FollowersListView.as_view(), name='followers_list'),
    path('<str:username>/following/', FollowingListView.as_view(), name='following_list'),
    path('<str:username>/follow/', follow, name='follow'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):

    followers = models.ManyToManyField('self', symmetrical=False, related_name='following', blank=True)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

User = get_user_model()

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, ListView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .forms import SignUpForm, CustomAuthenticationForm
from items.models import Item
from .models import CustomUser

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')
    template_name = 'signup.html'

class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'login.html'

class CustomLogoutView(LogoutView):
    pass

class LikedItemsListView(ListView):
    model = Item
    template_name = 'liked_items_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        user = get_object_or_404(CustomUser, username=self.kwargs['username'])
        return user.liked_items.all()

class ProfileView(TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_user = get_object_or_404(CustomUser, username=self.kwargs['username'])
        context['profile_user'] = profile_user
        context['items_for_sale'] = Item.objects.filter(author=profile_user)

        if self.request.user.is_authenticated:
            context['is_following'] = profile_user.followers.filter(id=self.request.user.id).exists()

        return context

class FollowersListView(ListView):
    model = CustomUser
    template_name = 'followers_list.html'
    context_object_name = 'followers'

    def get_queryset(self):
        user = get_object_or_404(CustomUser, username=self.kwargs['username'])
        return user.followers.all()

class FollowingListView(ListView):
    model = CustomUser
    template_name = 'following_list.html'
    context_object_name = 'following'

    def get_queryset(self):
        user = get_object_or_404(CustomUser, username=self.kwargs['username'])
        return user.following.all()

@login_required
def follow(request, username):
    user_to_follow = get_object_or_404(CustomUser, username=username)
    if request.user != user_to_follow:
        if user_to_follow.followers.filter(id=request.user.id).exists():
            user_to_follow.followers.remove(request.user)
        else:
            user_to_follow.followers.add(request.user)
    return HttpResponseRedirect(reverse('users:profile', args=[username]))

users/templates/followers_list.html
{% extends 'base.html' %}

{% block title %}팔로워 목록{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>팔로워 목록</h2>
    <div class="list-group">
        {% for follower in followers %}
            <a href="{% url 'users:profile' username=follower.username %}" class="list-group-item list-group-item-action">{{ follower.username }}</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/following_list.html
{% extends 'base.html' %}

{% block title %}팔로우 목록{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>팔로우 목록</h2>
    <div class="list-group">
        {% for user in following %}
            <a href="{% url 'users:profile' username=user.username %}" class="list-group-item list-group-item-action">{{ user.username }}</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/liked_items_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2>찜한 물건 목록</h2>
    <div class="row">
        {% for item in items %}
            {% include "item_card.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-3">로그인</h2>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors.as_text }}
            </div>
        {% endif %}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% if form.username.errors %}
                <div class="invalid-feedback">
                    {{ form.username.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password.label_tag }}
            {{ form.password }}
            {% if form.password.errors %}
                <div class="invalid-feedback">
                    {{ form.password.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p class="mt-3">
        계정이 없으신가요 ? <a href="{% url 'users:signup' %}"> 회원가입 하기 </a>
    </p>
</div>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}프로필{% endblock %}

{% block content %}
<div class="container">
    <h1>프로필 정보</h1>
    <p><strong>사용자 이름:</strong> {{ profile_user.username }}</p>
    <p><strong>이메일:</strong> {{ profile_user.email }}</p>
    <p><strong>회원가입 날짜:</strong> {{ profile_user.date_joined|date:"Y년 m월 d일" }}</p>
    <p>찜한 물건 수: <a href="{% url 'users:liked_items_list' username=profile_user.username %}">{{ profile_user.liked_items.count }}</a></p>
    <p>팔로워 수: <a href="{% url 'users:followers_list' username=profile_user.username %}">{{ profile_user.followers.count }}</a></p>
    <p>팔로우 수: <a href="{% url 'users:following_list' username=profile_user.username %}">{{ profile_user.following.count }}</a></p>
    
    {% if request.user != profile_user and request.user.is_authenticated %}
        {% if is_following %}
            <form action="{% url 'users:follow' username=profile_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">언팔로우</button>
            </form>
        {% else %}
            <form action="{% url 'users:follow' username=profile_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">팔로우</button>
            </form>
        {% endif %}
    {% endif %}
    
    <h2>{{ profile_user.username }}가 판매 중인 물건들</h2>
    <div class="row">
        {% for item in items_for_sale %}
            {% include "item_card.html" with item=item %}
        {% empty %}
            <p>판매 중인 물건이 없습니다.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-3">Sign Up</h2>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% if form.username.errors %}
                <div class="invalid-feedback">
                    {{ form.username.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.email.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="invalid-feedback">
                    {{ form.password1.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="invalid-feedback">
                    {{ form.password2.errors.as_text }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">등록하기</button>
    </form>
</div>
{% endblock %}