items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('create/', views.item_create, name='item_create'),
    path('<int:item_id>/', views.item_detail, name='item_detail'),
    path('<int:item_id>/update/', views.item_update, name='item_update'),
    path('<int:item_id>/delete/', views.item_delete, name='item_delete'),
    path('<int:item_id>/toggle_like/', views.toggle_like, name='toggle_like'),
]

mainpage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

market_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('items/', include('items.urls')),
    path('users/', include('users.urls')),

]

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, CustomLogoutView, ProfileView, LikedItemsListView, FollowersListView, FollowingListView, follow


app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('<str:username>/liked-items/', LikedItemsListView.as_view(), name='liked_items_list'),
    path('<str:username>/followers/', FollowersListView.as_view(), name='followers_list'),
    path('<str:username>/following/', FollowingListView.as_view(), name='following_list'),
    path('<str:username>/follow/', follow, name='follow'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}마켓{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        header a {
            color: #fff; 
            text-decoration: none;
            font-size: 28px;
            font-weight: bold;
            padding: 5px 10px; 
            transition: color 0.3s ease-in-out;
        }
        header a:hover, header a:focus {
            color: blue; 
            text-decoration: none;
        }
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        nav ul li {
            display: inline;
            margin-right: 10px;
        }
        nav ul li a { 
            color: #fff;
            text-decoration: none;
            font-size: 24px; 
            transition: color 0.3s ease-in-out;
        }
        nav ul li a:hover, nav ul li a:focus {
            color: blue; 
            text-decoration: none;
        }
        main {
            padding: 20px;
        }
        .card {
            margin: 15px; 
            box-shadow: 0 4px 8px rgba(0,0,0,0.2); 
            width: calc(100% / 4 - 30px); 
        }
        .card-img-top {
            width: 100%; 
            height: 200px;
            object-fit: cover; 
        }
        .row {
            display: flex;
            flex-wrap: wrap;
            margin-right: -15px;
            margin-left: -15px;
        }
        .container {
            max-width: 1200px; 
            margin-top: 20px; 
        }
        .form-label {
            font-weight: bold;
            display: block; 
            margin-bottom: 0.5rem; 
        }
        .form-text {
            display: block; 
            margin-top: 0.25rem;
            margin-bottom: 1rem;
            color: #6c757d; 
        }
        .invalid-feedback {
            display: block;
            margin-top: 0.25rem; 
        }
        .toggle-like-btn {
        background-color: #28a745; 
        color: white;
        border: none;
        padding: 8px 16px;
        margin-top: 10px;
        cursor: pointer;
        border-radius: 20px; 
        font-size: 0.9rem;
        }

        .toggle-like-btn.liked {
        background-color: #dc3545; 
        }

        .img-fluid {
        max-height: 500px; 
        width: auto; 
        display: block; 
        margin: 0 auto;
        }
        
    </style>
</head>
<body>
    <header>
        <a href="{% url 'mainpage:index' %}" class="market-link">마켓</a>
        <nav>
            <ul style="line-height: 40px; font-family: Arial, sans-serif;">
                {% if request.user.is_authenticated %}
                    <li>
                        <form action="{% url 'items:item_create' %}" method="get" style="display: inline;">
                            <button type="submit" class="btn btn-link" style="color: white; text-decoration: none; font-size: 24px; padding: 5px 10px; vertical-align: middle; border: none; background: none; font-weight: bold;">물건 등록</button>
                        </form>
                    </li>
                    <li>
                        <a href="{% url 'users:profile' username=request.user.username %}" class="btn btn-link" style="color: white; text-decoration: none; font-size: 24px; padding: 5px 10px; vertical-align: middle; border: none; background: none; font-weight: bold;">마이페이지</a>
                    </li>
                    <li>
                        <form action="{% url 'users:logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link" style="color: white; text-decoration: none; font-size: 24px; padding: 5px 10px; vertical-align: middle; border: none; background: none; font-weight: bold;">로그아웃</button>
                        </form>
                    </li>
                {% else %}
                    <li>
                        <form action="{% url 'users:login' %}" method="get" style="display: inline;">
                            <button type="submit" class="btn btn-link" style="color: white; text-decoration: none; font-size: 24px; padding: 5px 10px; vertical-align: middle; border: none; background: none; font-weight: bold;">로그인</button>
                        </form>
                    </li>
                    <li>
                        <form action="{% url 'users:signup' %}" method="get" style="display: inline;">
                            <button type="submit" class="btn btn-link" style="color: white; text-decoration: none; font-size: 24px; padding: 5px 10px; vertical-align: middle; border: none; background: none; font-weight: bold;">회원가입</button>
                        </form>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    
    
    
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="/static/js/app.js"></script>
</body>
</html>